# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e17d137ac1c9cdccc4f8fde23aa3a6901472cf7725c295af31f7236e8e31ac923581c310fff310bb1fce26595b8b386f433f4339936e91fe1d3f257e0ccaac5e

test:
  secret_key_base: fa8e9d7291eebd181dc3248b87ad408525a12a6da5782fe57b96670bcc80b0565555fc6a24d9f820e7b3b19b5d9dc0d04c63852d923650c1c0214174b40b0309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
